In [4]:
import pandas as pd
property_data = pd.read_csv('data/Property_Assessment_Data_(Current_Calendar_Year)_20260729.csv')
property_data.head()

C:\Users\tcaron\AppData\Local\Temp\ipykernel_65604\4030201220.py:2: DtypeWarning: Columns (0: Suite) have mixed types. Specify dtype option on import or set low_memory=False.
  property_data = pd.read_csv('data/Property_Assessment_Data_(Current_Calendar_Year)_20260729.csv')

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
0,4058129,NaN,870.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,165000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
1,4058137,NaN,872.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,165000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
2,4058145,NaN,874.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,166500,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
3,4058152,NaN,876.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,162000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
4,4058160,NaN,878.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,169500,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)

In [5]:
property_data.shape

(439635, 19)

In [6]:
property_data.describe()

,Account Number,House Number,Neighbourhood ID,Assessed Value,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude
count,4.396350e+05,393155.000000,430741.000000,4.396350e+05,439635.000000,1094.000000,286.000000,439635.000000,439635.000000
mean,8.021332e+06,7688.243443,4276.863561,5.418078e+05,99.952702,18.027422,3.206294,53.516821,-113.514888
std,3.264502e+06,5511.594200,1757.801496,3.461183e+06,1.228894,15.564439,3.601573,0.069158,0.085950
min,1.001007e+06,1.000000,1010.000000,0.000000e+00,40.000000,1.000000,1.000000,53.338595,-113.713318
25%,5.068152e+06,2503.000000,2660.000000,1.975000e+05,100.000000,3.000000,1.000000,53.456352,-113.574679
50%,9.993366e+06,7812.000000,4487.000000,3.970000e+05,100.000000,14.000000,1.500000,53.518836,-113.510802
75%,1.030951e+07,11421.000000,5579.000000,5.295000e+05,100.000000,33.000000,4.000000,53.572217,-113.448473
max,1.149918e+07,51175.000000,8889.000000,1.285146e+09,100.000000,50.000000,25.000000,53.715150,-113.278411

In [7]:
property_data["Neighbourhood"].unique()

<StringArray>
[                   'ABBOTTSFIELD',                          'ALBANY',
                  'ALBERTA AVENUE',         'ALBERTA PARK INDUSTRIAL',
                           'ALCES',                      'ALDERGROVE',
                          'ALLARD',                       'ALLENDALE',
                       'AMBLESIDE',                  'ANTHONY HENDAY',
 ...
               'WILSON INDUSTRIAL',                      'WINDERMERE',
                    'WINDSOR PARK', 'WINTERBURN INDUSTRIAL AREA EAST',
 'WINTERBURN INDUSTRIAL AREA WEST',                       'WOODCROFT',
        'YELLOWHEAD CORRIDOR EAST',        'YELLOWHEAD CORRIDOR WEST',
                            'YORK',           'YOUNGSTOWN INDUSTRIAL']
Length: 409, dtype: str

In [9]:
downtown_properties = property_data[property_data['Neighbourhood'] == 'DOWNTOWN']
print(f'Number of properties in downtown Edmonton {downtown_properties.shape[0]}')

Number of properties in downtown Edmonton 11216

In [20]:
sorted_downtown = downtown_properties.sort_values(by='Assessed Value', ascending=False)
sorted_downtown[['House Number', 'Street Name', 'Assessed Value']].head(10).style.format({'House Number': '{:.0f}', 'Assessed Value': '${:,.0f}'})

In [26]:
avg_by_neighbourhood = property_data.groupby('Neighbourhood')['Assessed Value'].agg(['mean', 'median', 'count'])
avg_by_neighbourhood.sort_values('mean', ascending=False).head(10).style.format({
    'mean': '${:,.0f}', 'median': '${:,.0f}', 'count': '{:.0f}'
})